sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  redis:
    host: localhost
    port: 6379
    database: 10

  wechat:
    appid: wx0ac75175e8be772a # 小程序appid
    secret: 65c26463ebff432db3b14bf1bc7ab448 # 小程序密钥
    mchid: 1561414331                 # 微信商户号
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606 #商户证书序列号
#    privateKeyFilePath: D:\pay\apiclient_key.pem  #商户私钥文件路径
    apiV3Key: CZBK51236435wxpay435434323FFDuv3 #APIv3密钥（32位）
#    weChatPayCertFilePath: D:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem #微信平台公钥证书路径
    notifyUrl: https://6619cf50.r6.cpolar.to/notify/paySuccess #支付成功回调地址
    refundNotifyUrl: https://6619cf50.r6.cpolar.top/notify/refundSuccess #退款回调地址
